server:
  port: 9001

spring:
  application:
    name: members

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery:8761/eureka

